# Generated by Django 3.2.2 on 2022-03-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
